# @package _global_

# Model specifications with thinking budgets for scaffolder models
model_specs:
  opus:
    name: "opus"
    thinking_budget: 10000
  sonnet:
    name: "sonnet" 
    thinking_budget: 10000
  opus-nothink:
    name: "opus"
    thinking_budget: 0
  sonnet-nothink:
    name: "sonnet" 
    thinking_budget: 0
  haiku:
    name: "haiku"
  gpt-4o:
    name: "gpt-4o"
    thinking_budget: 0
  gpt-4:
    name: "gpt-4"
    thinking_budget: 0
  gpt-5:
    name: "gpt-5"
    thinking_budget: 1
  gpt-5-mini:
    name: "gpt-5-mini"
    thinking_budget: 1
  gpt-5-nano:
    name: "gpt-5-mini"
    thinking_budget: 1
  gpt-5-nothink:
    name: "gpt-5"
    thinking_budget: 0
  gpt-5-mini-nothink:
    name: "gpt-5-mini"
    thinking_budget: 0
  gpt-5-nano-nothink:
    name: "gpt-5-nano"
    thinking_budget: 0
  v3:
    name: "v3"
    thinking_budget: 0
  r1:
    name: "r1"
    thinking_budget: 0  # Thinking budget has no effect
  mock:
    name: "mock"
    thinking_budget: 0
  human:
    name: "human"
    thinking_budget: 0

# Default selections
scaffolder: sonnet
executor: haiku
strategy: ${scaffolder}