name: scaffold-learning
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.6.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - -e .[dev,reward-models,analysis]  # installs from pyproject.toml

