[project]
name = "scaffold-learning"
version = "0.1.0"
dependencies = [
    "anthropic",
    "openai",
    "python-dotenv"
]

[tool.setuptools]
py-modules = ["generate_scaffold_script", "llm_interfaces"]