# @package _global_
defaults:
  - default
  - override /hydra/launcher: joblib

hydra:
  launcher:
    n_jobs: 4  # Number of parallel workers
    batch_size: auto  # Corrected field name
    pre_dispatch: 2*n_jobs  # Controls memory usage
    timeout: null  # Timeout per job in seconds

# All other settings (run, sweep, job) inherited from default