defaults:
  - model: default
  - experiment: default
  - runtime: default
  - _self_

experiment_name: ???  # Must be provided - no default

# Models - these get overridden by model config but provide fallbacks
scaffolder: haiku
executor: haiku
strategy: ${scaffolder}  # Defaults to same as scaffolder
strategy_batch_size: null