defaults:
  - model: default
  - experiment: default
  - runtime: default
  - _self_

experiment_name: ???  # Must be provided - no default

# Docker configuration
build_docker: true  # Whether to build Docker image before running

# Models - these get overridden by model config but provide fallbacks
scaffolder: haiku
executor: haiku
strategy: ${scaffolder}  # Defaults to same as scaffolder

# Reasoning effort configuration
executor_reasoning_effort: "minimal"  # Default for executors
scaffolder_reasoning_effort: "medium"  # Default for scaffolders/strategy models